name: CI + CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - name: Send email notification
        if: always()   # 无论成功失败都发；如果只想失败发，用 failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.larksuite.com
          server_port: 465
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          subject: "CI result: ${{ job.status }} for ${{ github.repository }}"
          to: "jiangwt23@mails.tsinghua.edu.cn"
          from: "CI Bot <bot@mail.lveying.live>"
          body: |
            Workflow: ${{ github.workflow }}
            Status:   ${{ job.status }}
            Repo:     ${{ github.repository }}
            Commit:   ${{ github.sha }}
  deploy:
    needs: build          # 只有 build 成功才会跑
    runs-on: self-hosted  # 跑在你的 Windows 机器上

    steps:
      - name: Run deploy script
        shell: powershell
        run: |
          & "C:\Users\LUEYING\server\lveying\.github\scripts\deploy.ps1"
