name: CI + CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
  send_email:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit message
        id: last_commit
        run: |
          msg=$(git log -1 --pretty=%B)
          # 去掉可能的换行，避免邮件标题炸掉
          msg="${msg//'%'/'%25'}"
          msg="${msg//$'\n'/' '}"
          msg="${msg//$'\r'/' '}"
          echo "message=$msg" >> $GITHUB_OUTPUT

      - name: Send email notification
        if: always()   # 无论成功失败都发；如果只想失败发，用 failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.larksuite.com
          server_port: 465
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          subject: >
            掠影网站自动部署报告 - ${{ job.status }} -${{github.ref_name}} - ${{ steps.last_commit.outputs.message }}

          to: |
            "jiangwt23@mails.tsinghua.edu.cn"
          cc: |
            "gaw23@mails.tsinghua.edu.cn",
            "wjiang0415@outlook.com",
            "wjiang0415@gmail.com"

          from: "CI Bot <bot@mail.lveying.live>"
          body: |
            你好，管理员：
            掠影网站在分支 ${{ github.ref_name }} 上的自动部署已完成，状态为 ${{ job.status }}。以下为具体信息。

            仓库:   ${{ github.repository }}
            分支:   ${{ github.ref_name }}
            提交人: ${{ github.actor }}
            SHA:    ${{ github.sha }}
            Commit message:
            ${{ steps.last_commit.outputs.message }}

            工作流: ${{ github.workflow }}
            运行ID: ${{ github.run_id }}

            本邮件由系统自动发送。
  deploy:
    needs: build
    runs-on: self-hosted

    steps:

      - name: Run deploy script
        shell: powershell
        run: |
          sudo powershell -ExecutionPolicy Bypass -File "C:\Users\LUEYING\deploy\deploy.ps1"